### ISSUE TITLE
Support for cross dissolve TO CLIP

### ISSUE THREAD

**Issue by MisakiAkatsuki** [bradcordeiro/edl-genius#1]
```
000001  AX       V     C        00:00:04:18 00:00:04:18 01:01:25:10 01:01:25:10
FCM: NON-DROP FRAME
000002  AX       V     D    024 00:00:00:10 00:00:02:14 01:01:25:10 01:01:27:14
EFFECTS NAME IS CROSS DISSOLVE
* FROM CLIP NAME: Clip_01.mov
* TO CLIP NAME: Clip_02.mov
```

I'd like to get the information of the cross dissolve TO CLIP(Clip_02.mov) in an EDL like the one above as Event Class.
Would you be willing to respond to that?
Thank you.

**Comment by bradcordeiro** [comment]
Yes, I can work on this! If you have a sample EDL you could share with some cross dissolves it would help me, but I can get started on it now.

**Comment by bradcordeiro** [comment]
Okay, I have added this in version 3.3.0.

**Comment by MisakiAkatsuki** [comment]
Thank you!!
