### ISSUE TITLE
npm install error on Windows10 1909 (Build 18363.778)

### ISSUE THREAD

**Issue by MisakiAkatsuki** [bradcordeiro/edl-genius#2]
Hi,

I'm having installation problems.
Is it possible to install without build?

This is the error message.

C:\Users\USER\test>npm install --save edl-genius

detect-character-encoding@0.8.0 install C:\Users\USER\test\node_modules\detect-character-encoding
node-gyp rebuild

> C:\Users\USER\test\node_modules\detect-character-encoding>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> Warning: Missing input files:
> C:\Users\USER\test\node_modules\detect-character-encoding\build\vendor\icu\..\..\..\vendor\icu\no-op.cc
> C:\Users\USER\test\node_modules\detect-character-encoding\build\vendor\icu\..\..\..\vendor\icu\iculslocs.cc
> このソリューション内のプロジェクトを 1 度に 1 つずつビルドします。並行ビルドを有効にするには、"/m" スイッチを追加してください。
>   ucsdet.cpp
>   csrutf8.cpp
>   csdetect.cpp
>   csrucode.cpp
>   ucln_in.cpp
>   csrsbcs.cpp
>   csr2022.cpp
>   inputext.cpp
>   csrmbcs.cpp
>   csmatch.cpp
>   csrecog.cpp
>   win_delay_load_hook.cc
>   icui18n.vcxproj -> C:\Users\USER\test\node_modules\detect-character-encoding\build\Release\\icui18n.lib
>   uarrsort.cpp
>   cstring.cpp
>   ucln_cmn.cpp
>   putil.cpp
>   uenum.cpp
>   cmemory.cpp
>   umutex.cpp
>   utypes.cpp
>   uobject.cpp
>   win_delay_load_hook.cc
>   icuucx.vcxproj -> C:\Users\USER\test\node_modules\detect-character-encoding\build\Release\\icuucx.lib
>   icuWrapper.cpp
>   win_delay_load_hook.cc
>      ライブラリ C:\Users\USER\test\node_m
>   odules\detect-character-encoding\build\Release\icuWrapper.lib とオブジェクト C:\User
>   s\USER\test\node_modules\detect-ch
>   aracter-encoding\build\Release\icuWrapper.exp を作成中
> icui18n.lib(csmatch.obj) : error LNK2001: 外部シンボル "ucnv_close_61" は未解決です。 [C:\Us
> ers\USER\test\node_modules\detect-ch
> aracter-encoding\build\icuWrapper.vcxproj]
> icui18n.lib(csmatch.obj) : error LNK2001: 外部シンボル "ucnv_toUChars_61" は未解決です。 [C:
> \Users\USER\test\node_modules\detect
> -character-encoding\build\icuWrapper.vcxproj]
> icui18n.lib(csmatch.obj) : error LNK2001: 外部シンボル "ucnv_open_61" は未解決です。 [C:\Use
> rs\USER\test\node_modules\detect-cha
> racter-encoding\build\icuWrapper.vcxproj]
> icuucx.lib(uenum.obj) : error LNK2001: 外部シンボル "u_UCharsToChars_61" は未解決です。 [C:\
> Users\USER\test\node_modules\detect-
> character-encoding\build\icuWrapper.vcxproj]
> icuucx.lib(uenum.obj) : error LNK2001: 外部シンボル "u_charsToUChars_61" は未解決です。 [C:\
> Users\USER\test\node_modules\detect-
> character-encoding\build\icuWrapper.vcxproj]
> icuucx.lib(ucln_cmn.obj) : error LNK2001: 外部シンボル "utrace_cleanup_61" は未解決です。 [C
> :\Users\USER\test\node_modules\detec
> t-character-encoding\build\icuWrapper.vcxproj]
> C:\Users\USER\test\node_modules\dete
> ct-character-encoding\build\Release\icuWrapper.node : fatal error LNK1120: 6 件の
> 未解決の外部参照 [C:\Users\USER\test\node_mo
> dules\detect-character-encoding\build\icuWrapper.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:191:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Windows_NT 10.0.18363
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\USER\test\node_modules\detect-character-encoding
> gyp ERR! node -v v10.20.1
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok
> npm WARN export-data@1.0.0 No description
> npm WARN export-data@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! detect-character-encoding@0.8.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the detect-character-encoding@0.8.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2020-05-07T09_31_11_486Z-debug.log
> 
> C:\Users\USER\test>
>

**Comment by bradcordeiro** [comment]
This looks like an error in one of the dependencies, "detect-character-encoding", used to detect the text encoding of EDL files. edl-genius itself doesn't require any building. I don't usually develop on Windows but I have a Windows computer so I can try and troubleshoot on this week.

**Comment by MisakiAkatsuki** [comment]
Okey, Thank you.

**Comment by asudakov** [comment]
"detect-character-encoding" is not available on Windows [and some other platforms].

This stupid dependency makes this package not cross-platform.

Please remove this "stupid dependency".

**Comment by bradcordeiro** [comment]
Sorry it's been a while, but I finally came back to this package after busy time and I believe this is resolved, "detect-character-encoding" has been removed in 3.4.5.

**Comment by MisakiAkatsuki** [comment]
I'm very happy with the update!
I'm going to check it out next time.
