### ISSUE TITLE
Doesn't work at all with 59.94 frame rate

### ISSUE THREAD

**Issue by asudakov** [bradcordeiro/edl-genius#3]
Glancing into the code the package is limited to 29.97 frame rate only.

Totally useless with 59.94 frame rate!

**Comment by asudakov** [comment]
Bad coding is in the way Timecode objects are initialized without passing frame rate and assuming 29.97 frame-rate.

**Comment by bradcordeiro** [comment]
Feel free to submit a pull request.

**Comment by asudakov** [comment]
The problem appears to be with CMX3600Parser changeFrameRate (line 95)`  return (line === 'FCM: NON-DROP FRAME' ? 30 : 29.97);
`
It overrides frame rate set on EditDecisionList.

I don't know how EDL spec deals with 60 fps, but removing FCM: NON-DROP FRAME from my EDLs makes it work for 59.94 fps EDLs.

**Comment by bradcordeiro** [comment]
I believe this is resolved in 3.4.5, "FCM: NON-DROP FRAME" caused the source clip's timecode frame rate to be set to 30 non-drop regardless of the original rate set.

**Comment by bradcordeiro** [comment]
This was fixed in commit [6f3c0c19f417002a2304601327b031a939909b14](https://github.com/bradcordeiro/edl-genius/commit/6f3c0c19f417002a2304601327b031a939909b14).
